apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-icloud-nfs
spec:
  capacity: { storage: 1Ti }
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions: [nfsvers=4.1, noatime]
  nfs:
    server: 192.168.10.33
    path: /mnt/Storage/immich/icloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: icloud-photos
  namespace: immich
spec:
  accessModes: [ReadWriteMany]
  storageClassName: ""
  volumeName: immich-icloud-nfs
  resources: { requests: { storage: 1Ti } }