apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anytype
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Astri4-4/homelab-k8s
    targetRevision: master
    path: apps/anytype
  destination:
    server: https://kubernetes.default.svc
    namespace: anytype
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
