apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-network-policies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes-sigs/kube-network-policies
    targetRevision: main
    path: charts/kube-network-policies
    helm:
      releaseName: kube-network-policies
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }