# À placer dans infra/argocd-apps/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: music
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/astri4-4/homelab-k8s.git   # adapter
    targetRevision: master
    path: apps/music                                        # adapter au layout du repo
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true