apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: any-sync-bundle
  namespace: anytype
spec:
  serviceName: any-sync-bundle
  replicas: 1
  selector:
    matchLabels:
      app: any-sync-bundle
  template:
    metadata:
      labels:
        app: any-sync-bundle
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: talosnode1   # pin sur le même nœud que l'IP annoncée
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: any-sync-bundle
          image: ghcr.io/grishy/any-sync-bundle:1.6.0-2026-08-18
          env:
            - name: ANY_SYNC_BUNDLE_INIT_EXTERNAL_ADDRS
              value: "192.168.10.120"
          ports:
            - name: drpc
              containerPort: 33010
              protocol: TCP
            - name: quic
              containerPort: 33020
              protocol: UDP
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 5Gi
