apiVersion: v1
kind: Namespace
metadata:
  name: anytype
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: any-sync-bundle
  namespace: anytype
spec:
  serviceName: any-sync-bundle
  replicas: 1
  selector:
    matchLabels:
      app: any-sync-bundle
  template:
    metadata:
      labels:
        app: any-sync-bundle
    spec:
      containers:
        - name: any-sync-bundle
          image: ghcr.io/grishy/any-sync-bundle:1.2.1-2025-12-10
          env:
            - name: ANY_SYNC_BUNDLE_INIT_EXTERNAL_ADDRS
              value: "192.168.1.120"   # IP LAN à ajuster
          ports:
            - name: drpc
              containerPort: 33010
              protocol: TCP
            - name: quic
              containerPort: 33020
              protocol: UDP
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: any-sync-bundle
  namespace: anytype
spec:
  type: NodePort
  selector:
    app: any-sync-bundle
  ports:
    - name: drpc
      port: 33010
      targetPort: 33010
      protocol: TCP
      nodePort: 30010
    - name: quic
      port: 33020
      targetPort: 33020
      protocol: UDP
      nodePort: 30020
