---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: atm10-rcon
  namespace: minecraft
spec:
  encryptedData:
    RCON_PASSWORD: AgBQ94o41DowWq1faiwpntLGkvLSyKs/XgwzDepQxlIwN8TD9Vs/+sD2Sop4xbGZ59gD9055AV6cz2tX6qLFemV9YfctjWjXmeQHjZ0M8CF0msX4Mk+e83T0v5tB7N95lCVHYLJ6fOK5XVOZPQ6Hn2a3O8+4wAyRjORD2r4U0UohYvkQhGvZTV/7Y+OdFdw11RSgFB/u4du/Ti2FQqoGF/2j4ZLmzcib1SawcUOSxgiV2Fw1xwpvVycibhxIT/02sTnvgLa6Ag9EsdbfpfunLfDB5onajMx9xx7cqCZlgpP2omTpLyKuGXWMN+dD446zqHTJf70MCH0eb2RG/CltEi3XDCQsjxI4rQdyiEYLTXSF/9uQ1b+JX+pqU2DemVERSub0Rk40rSf08mwQuqHy1CC8Ezr25em2H7qd6Xjpl/mJ1FmlXObGHUavG8CTxCmitwXl//ib9bMA8MNtv0PoPX9CWFxWA0Cq5auLnYBOK6pJXEuAqRsdS6rAak3/BqEPtlDdcYQ75MP0irP0R13t/xxPSmbsZJ2EggFCvXBu4uShl+fIRdMZSMcUpedXRxUXIqocrfsEeoRGmWbfFYNWVome8gB+prObdkLEJ0vh+7o0pX0y2NuUkdyFco+p9u4dtYJhY9lqA7RuIA7P4f7D3tT0QzumsVwYgAD8KWpuc4VP9IPmswTrbSFi+8barI2csuFL/C9PzSP2srQcTeAUR3+lT8K2OJIf1hQfpOz1T+mwaA==
  template:
    metadata:
      name: atm10-rcon
      namespace: minecraft
